local M = {}

function M.get(c)
  return {
    -- ===== Editor =====
    Normal       = { fg = c.fg, bg = c.bg },
    NormalNC     = { fg = c.fg, bg = c.bg },
    NormalFloat  = { fg = c.fg, bg = c.bg },
    FloatBorder  = { fg = c.bg_alt, bg = c.bg },
    FloatTitle   = { fg = c.orange, bg = c.bg, bold = true },

    Cursor       = { fg = c.bg, bg = c.cursor },
    lCursor      = { fg = c.bg, bg = c.cursor },
    CursorIM     = { fg = c.bg, bg = c.cursor },
    TermCursor   = { fg = c.bg, bg = c.cursor },

    CursorLine   = { bg = c.bg_alt },
    CursorColumn = { bg = c.bg_alt },
    ColorColumn  = { bg = c.bg_alt },
    Visual       = { fg = c.sel_fg, bg = c.sel_bg },
    VisualNOS    = { fg = c.sel_fg, bg = c.sel_bg },

    LineNr       = { fg = c.bg_alt, bg = c.bg },
    CursorLineNr = { fg = c.fg, bg = c.bg, bold = true },
    SignColumn   = { fg = c.fg_dim, bg = c.bg },
    FoldColumn   = { fg = c.bg_alt, bg = c.bg },
    Folded       = { fg = c.fg_dim, bg = c.bg_alt },

    Search       = { fg = c.sel_fg, bg = c.orange },
    IncSearch    = { fg = c.sel_fg, bg = c.orange_dark },
    CurSearch    = { fg = c.sel_fg, bg = c.orange_dark, bold = true },
    Substitute   = { fg = c.sel_fg, bg = c.red },
    MatchParen   = { fg = c.orange, bold = true, underline = true },

    VertSplit    = { fg = c.bg_alt, bg = c.bg },
    WinSeparator = { fg = c.bg_alt, bg = c.bg },

    StatusLine   = { fg = c.fg, bg = c.bg_alt },
    StatusLineNC = { fg = c.fg_dim, bg = c.bg },
    WinBar       = { fg = c.fg, bg = c.bg, bold = true },
    WinBarNC     = { fg = c.fg_dim, bg = c.bg },

    TabLine      = { fg = c.fg_dim, bg = c.bg_alt },
    TabLineFill  = { fg = c.fg_dim, bg = c.bg },
    TabLineSel   = { fg = c.bg, bg = c.orange, bold = true },

    Pmenu        = { fg = c.fg, bg = c.bg_alt },
    PmenuSel     = { fg = c.bg, bg = c.orange, bold = true },
    PmenuSbar    = { bg = c.bg_alt },
    PmenuThumb   = { bg = c.orange },
    PmenuKind    = { fg = c.cyan, bg = c.bg_alt },
    PmenuExtra   = { fg = c.fg_dim, bg = c.bg_alt },

    WildMenu     = { fg = c.bg, bg = c.orange },
    QuickFixLine = { bg = c.bg_alt, bold = true },

    Title        = { fg = c.orange_dark, bold = true },
    Directory    = { fg = c.orange },
    Conceal      = { fg = c.bg_alt },
    NonText      = { fg = c.bg_alt },
    EndOfBuffer  = { fg = c.bg },
    SpecialKey   = { fg = c.bg_alt },
    Whitespace   = { fg = c.bg_alt },

    ErrorMsg     = { fg = c.red, bold = true },
    WarningMsg   = { fg = c.orange_dark, bold = true },
    ModeMsg      = { fg = c.fg, bold = true },
    MoreMsg      = { fg = c.teal },
    Question     = { fg = c.cyan },

    SpellBad     = { sp = c.red, undercurl = true },
    SpellCap     = { sp = c.orange, undercurl = true },
    SpellRare    = { sp = c.cyan, undercurl = true },
    SpellLocal   = { sp = c.teal, undercurl = true },

    -- ===== Legacy syntax =====
    Comment      = { fg = c.bg_alt, italic = true },

    Constant     = { fg = c.red },
    String       = { fg = c.teal },
    Character    = { fg = c.teal },
    Number       = { fg = c.red },
    Boolean      = { fg = c.red },
    Float        = { fg = c.red },

    Identifier   = { fg = c.red },
    Function     = { fg = c.orange },

    Statement    = { fg = c.teal_dim },
    Conditional  = { fg = c.teal_dim },
    Repeat       = { fg = c.teal_dim },
    Label        = { fg = c.orange_dark },
    Operator     = { fg = c.fg },
    Keyword      = { fg = c.teal_dim },
    Exception    = { fg = c.red },

    PreProc      = { fg = c.teal_dim },
    Include      = { fg = c.teal_dim },
    Define       = { fg = c.teal_dim },
    Macro        = { fg = c.orange_dark },
    PreCondit    = { fg = c.teal_dim },

    Type         = { fg = c.orange_dark },
    StorageClass = { fg = c.orange_dark },
    Structure    = { fg = c.orange_dark },
    Typedef      = { fg = c.orange_dark },

    Special      = { fg = c.orange },
    SpecialChar  = { fg = c.red },
    Tag          = { fg = c.red },
    Delimiter    = { fg = c.fg },
    SpecialComment = { fg = c.cyan, italic = true },
    Debug        = { fg = c.red },

    Underlined   = { fg = c.cyan, underline = true },
    Ignore       = { fg = c.bg_alt },
    Error        = { fg = c.red, bold = true },
    Todo         = { fg = c.bg, bg = c.orange, bold = true },

    -- ===== Treesitter =====
    ["@comment"]              = { link = "Comment" },
    ["@comment.documentation"] = { fg = c.bg_alt, italic = true },
    ["@comment.todo"]         = { fg = c.bg, bg = c.orange, bold = true },
    ["@comment.warning"]      = { fg = c.bg, bg = c.orange_dark, bold = true },
    ["@comment.error"]        = { fg = c.bg, bg = c.red, bold = true },
    ["@comment.note"]         = { fg = c.bg, bg = c.cyan, bold = true },

    ["@variable"]             = { fg = c.red },
    ["@variable.builtin"]     = { fg = c.red, italic = true },
    ["@variable.parameter"]   = { fg = c.fg },
    ["@variable.member"]      = { fg = c.fg },

    ["@constant"]             = { fg = c.red },
    ["@constant.builtin"]     = { fg = c.red },
    ["@constant.macro"]       = { fg = c.orange_dark },

    ["@module"]               = { fg = c.orange_dark },
    ["@label"]                = { fg = c.orange_dark },

    ["@string"]               = { fg = c.teal },
    ["@string.documentation"] = { fg = c.teal },
    ["@string.regexp"]        = { fg = c.teal },
    ["@string.escape"]        = { fg = c.red },
    ["@string.special"]       = { fg = c.teal },
    ["@string.special.symbol"] = { fg = c.teal },
    ["@string.special.url"]   = { fg = c.red, underline = true },

    ["@character"]            = { fg = c.teal },
    ["@character.special"]    = { fg = c.red },

    ["@boolean"]              = { fg = c.red },
    ["@number"]               = { fg = c.red },
    ["@number.float"]         = { fg = c.red },

    ["@type"]                 = { fg = c.orange_dark },
    ["@type.builtin"]         = { fg = c.orange_dark },
    ["@type.definition"]      = { fg = c.orange_dark },

    ["@attribute"]            = { fg = c.orange },
    ["@property"]             = { fg = c.fg },

    ["@function"]             = { fg = c.orange },
    ["@function.builtin"]     = { fg = c.orange },
    ["@function.call"]        = { fg = c.orange },
    ["@function.macro"]       = { fg = c.orange_dark },
    ["@function.method"]      = { fg = c.orange },
    ["@function.method.call"] = { fg = c.orange },

    ["@constructor"]          = { fg = c.red },
    ["@operator"]             = { fg = c.fg },

    ["@keyword"]              = { fg = c.teal_dim },
    ["@keyword.coroutine"]    = { fg = c.teal_dim },
    ["@keyword.function"]     = { fg = c.teal_dim },
    ["@keyword.operator"]     = { fg = c.teal_dim },
    ["@keyword.import"]       = { fg = c.teal_dim },
    ["@keyword.type"]         = { fg = c.teal_dim },
    ["@keyword.modifier"]     = { fg = c.teal_dim },
    ["@keyword.repeat"]       = { fg = c.teal_dim },
    ["@keyword.return"]       = { fg = c.teal_dim },
    ["@keyword.debug"]        = { fg = c.red },
    ["@keyword.exception"]    = { fg = c.red },
    ["@keyword.conditional"]  = { fg = c.teal_dim },
    ["@keyword.directive"]    = { fg = c.teal_dim },
    ["@keyword.directive.define"] = { fg = c.teal_dim },

    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.bracket"]   = { fg = c.fg },
    ["@punctuation.special"]   = { fg = c.fg },

    ["@markup.strong"]        = { fg = c.red, bold = true },
    ["@markup.italic"]        = { fg = c.red, italic = true },
    ["@markup.strikethrough"] = { fg = c.fg, strikethrough = true },
    ["@markup.underline"]     = { fg = c.cyan, underline = true },
    ["@markup.heading"]       = { fg = c.orange_dark, bold = true },
    ["@markup.heading.1"]     = { fg = c.orange_dark, bold = true },
    ["@markup.heading.2"]     = { fg = c.orange, bold = true },
    ["@markup.heading.3"]     = { fg = c.cyan, bold = true },
    ["@markup.heading.4"]     = { fg = c.teal, bold = true },
    ["@markup.heading.5"]     = { fg = c.teal_dim, bold = true },
    ["@markup.heading.6"]     = { fg = c.fg_dim, bold = true },
    ["@markup.quote"]         = { fg = c.fg_dim, italic = true },
    ["@markup.math"]          = { fg = c.cyan },
    ["@markup.link"]          = { fg = c.red },
    ["@markup.link.label"]    = { fg = c.red },
    ["@markup.link.url"]      = { fg = c.red, underline = true },
    ["@markup.raw"]           = { fg = c.teal },
    ["@markup.raw.block"]     = { fg = c.teal },
    ["@markup.list"]          = { fg = c.fg },
    ["@markup.list.checked"]  = { fg = c.teal },
    ["@markup.list.unchecked"] = { fg = c.orange_dark },

    ["@tag"]                  = { fg = c.red },
    ["@tag.builtin"]          = { fg = c.red },
    ["@tag.attribute"]        = { fg = c.orange },
    ["@tag.delimiter"]        = { fg = c.fg },

    ["@diff.plus"]            = { fg = c.teal },
    ["@diff.minus"]           = { fg = c.red },
    ["@diff.delta"]           = { fg = c.orange },

    -- ===== LSP semantic tokens =====
    ["@lsp.type.namespace"]   = { link = "@module" },
    ["@lsp.type.type"]        = { link = "@type" },
    ["@lsp.type.class"]       = { link = "@type" },
    ["@lsp.type.enum"]        = { link = "@type" },
    ["@lsp.type.interface"]   = { link = "@type" },
    ["@lsp.type.struct"]      = { link = "@type" },
    ["@lsp.type.parameter"]   = { link = "@variable.parameter" },
    ["@lsp.type.variable"]    = { link = "@variable" },
    ["@lsp.type.property"]    = { link = "@property" },
    ["@lsp.type.enumMember"]  = { link = "@constant" },
    ["@lsp.type.function"]    = { link = "@function" },
    ["@lsp.type.method"]      = { link = "@function.method" },
    ["@lsp.type.macro"]       = { link = "@function.macro" },
    ["@lsp.type.decorator"]   = { link = "@attribute" },
    ["@lsp.type.keyword"]     = { link = "@keyword" },
    ["@lsp.type.string"]      = { link = "@string" },
    ["@lsp.type.number"]      = { link = "@number" },
    ["@lsp.type.comment"]     = { link = "@comment" },
    ["@lsp.mod.deprecated"]   = { strikethrough = true },

    -- ===== Diagnostics =====
    DiagnosticError = { fg = c.red },
    DiagnosticWarn  = { fg = c.orange_dark },
    DiagnosticInfo  = { fg = c.cyan },
    DiagnosticHint  = { fg = c.fg },
    DiagnosticOk    = { fg = c.teal },

    DiagnosticVirtualTextError = { fg = c.red, bg = c.bg },
    DiagnosticVirtualTextWarn  = { fg = c.orange_dark, bg = c.bg },
    DiagnosticVirtualTextInfo  = { fg = c.cyan, bg = c.bg },
    DiagnosticVirtualTextHint  = { fg = c.fg, bg = c.bg },
    DiagnosticVirtualTextOk    = { fg = c.teal, bg = c.bg },

    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn  = { sp = c.orange_dark, undercurl = true },
    DiagnosticUnderlineInfo  = { sp = c.cyan, undercurl = true },
    DiagnosticUnderlineHint  = { sp = c.cyan, undercurl = true },
    DiagnosticUnderlineOk    = { sp = c.teal, undercurl = true },

    DiagnosticFloatingError = { fg = c.red },
    DiagnosticFloatingWarn  = { fg = c.orange_dark },
    DiagnosticFloatingInfo  = { fg = c.cyan },
    DiagnosticFloatingHint  = { fg = c.fg },
    DiagnosticFloatingOk    = { fg = c.teal },

    DiagnosticSignError = { fg = c.red, bg = c.bg },
    DiagnosticSignWarn  = { fg = c.orange_dark, bg = c.bg },
    DiagnosticSignInfo  = { fg = c.cyan, bg = c.bg },
    DiagnosticSignHint  = { fg = c.fg, bg = c.bg },
    DiagnosticSignOk    = { fg = c.teal, bg = c.bg },

    DiagnosticDeprecated  = { sp = c.fg_dim, strikethrough = true },
    DiagnosticUnnecessary = { fg = c.bg_alt },

    -- ===== LSP =====
    LspReferenceText  = { bg = c.bg_alt },
    LspReferenceRead  = { bg = c.bg_alt },
    LspReferenceWrite = { bg = c.bg_alt },
    LspSignatureActiveParameter = { fg = c.orange, bold = true },
    LspCodeLens       = { fg = c.bg_alt, italic = true },
    LspInlayHint      = { fg = c.bg_alt, bg = c.bg, italic = true },

    -- ===== Diff =====
    DiffAdd     = { bg = "#0a3a44" },
    DiffChange  = { bg = "#1a3a55" },
    DiffDelete  = { fg = c.red, bg = "#3a1a1a" },
    DiffText    = { bg = "#2a4a66", bold = true },

    Added       = { fg = c.teal },
    Changed     = { fg = c.orange },
    Removed     = { fg = c.red },

    -- ===== GitSigns =====
    GitSignsAdd          = { fg = c.teal, bg = c.bg },
    GitSignsChange       = { fg = c.orange, bg = c.bg },
    GitSignsDelete       = { fg = c.red, bg = c.bg },
    GitSignsAddNr        = { fg = c.teal },
    GitSignsChangeNr     = { fg = c.orange },
    GitSignsDeleteNr     = { fg = c.red },
    GitSignsAddLn        = { bg = "#0a3a44" },
    GitSignsChangeLn     = { bg = "#1a3a55" },
    GitSignsDeleteLn     = { bg = "#3a1a1a" },
    GitSignsCurrentLineBlame = { fg = c.bg_alt, italic = true },

    -- ===== Telescope =====
    TelescopeNormal         = { fg = c.fg, bg = c.bg },
    TelescopeBorder         = { fg = c.bg_alt, bg = c.bg },
    TelescopePromptNormal   = { fg = c.fg, bg = c.bg_alt },
    TelescopePromptBorder   = { fg = c.bg_alt, bg = c.bg_alt },
    TelescopePromptTitle    = { fg = c.bg, bg = c.orange, bold = true },
    TelescopePreviewTitle   = { fg = c.bg, bg = c.teal, bold = true },
    TelescopeResultsTitle   = { fg = c.bg, bg = c.cyan, bold = true },
    TelescopeSelection      = { fg = c.fg, bg = c.bg_alt, bold = true },
    TelescopeSelectionCaret = { fg = c.orange, bg = c.bg_alt },
    TelescopeMatching       = { fg = c.orange, bold = true },
    TelescopeMultiSelection = { fg = c.cyan },

    -- ===== NvimTree =====
    NvimTreeNormal           = { fg = c.fg, bg = c.bg },
    NvimTreeNormalNC         = { fg = c.fg, bg = c.bg },
    NvimTreeRootFolder       = { fg = c.orange_dark, bold = true },
    NvimTreeFolderName       = { fg = c.orange },
    NvimTreeOpenedFolderName = { fg = c.orange, bold = true },
    NvimTreeEmptyFolderName  = { fg = c.fg_dim },
    NvimTreeFolderIcon       = { fg = c.orange },
    NvimTreeFileIcon         = { fg = c.fg_dim },
    NvimTreeSpecialFile      = { fg = c.cyan, underline = true },
    NvimTreeGitDirty         = { fg = c.orange },
    NvimTreeGitNew           = { fg = c.teal },
    NvimTreeGitDeleted       = { fg = c.red },
    NvimTreeGitStaged        = { fg = c.teal },
    NvimTreeGitRenamed       = { fg = c.orange_dark },
    NvimTreeIndentMarker     = { fg = c.bg_alt },
    NvimTreeWinSeparator     = { fg = c.bg_alt, bg = c.bg },
    NvimTreeCursorLine       = { bg = c.bg_alt },

    -- ===== neo-tree =====
    NeoTreeNormal           = { fg = c.fg, bg = c.bg },
    NeoTreeNormalNC         = { fg = c.fg, bg = c.bg },
    NeoTreeDirectoryName    = { fg = c.orange },
    NeoTreeDirectoryIcon    = { fg = c.orange },
    NeoTreeRootName         = { fg = c.orange_dark, bold = true },
    NeoTreeFileName         = { fg = c.fg },
    NeoTreeFileIcon         = { fg = c.fg_dim },
    NeoTreeIndentMarker     = { fg = c.bg_alt },
    NeoTreeGitAdded         = { fg = c.teal },
    NeoTreeGitConflict      = { fg = c.orange_dark },
    NeoTreeGitDeleted       = { fg = c.red },
    NeoTreeGitModified      = { fg = c.orange },
    NeoTreeGitUntracked     = { fg = c.cyan },

    -- ===== which-key =====
    WhichKey            = { fg = c.orange },
    WhichKeyGroup       = { fg = c.cyan },
    WhichKeyDesc        = { fg = c.fg },
    WhichKeySeparator   = { fg = c.bg_alt },
    WhichKeyFloat       = { bg = c.bg },
    WhichKeyBorder      = { fg = c.bg_alt, bg = c.bg },

    -- ===== nvim-cmp / blink.cmp =====
    CmpItemAbbr            = { fg = c.fg },
    CmpItemAbbrDeprecated  = { fg = c.fg_dim, strikethrough = true },
    CmpItemAbbrMatch       = { fg = c.orange, bold = true },
    CmpItemAbbrMatchFuzzy  = { fg = c.orange, bold = true },
    CmpItemMenu            = { fg = c.fg_dim, italic = true },
    CmpItemKindDefault     = { fg = c.fg_dim },
    CmpItemKindKeyword     = { fg = c.teal_dim },
    CmpItemKindVariable    = { fg = c.red },
    CmpItemKindConstant    = { fg = c.red },
    CmpItemKindReference   = { fg = c.red },
    CmpItemKindValue       = { fg = c.red },
    CmpItemKindFunction    = { fg = c.orange },
    CmpItemKindMethod      = { fg = c.orange },
    CmpItemKindConstructor = { fg = c.red },
    CmpItemKindClass       = { fg = c.orange_dark },
    CmpItemKindInterface   = { fg = c.orange_dark },
    CmpItemKindStruct      = { fg = c.orange_dark },
    CmpItemKindEvent       = { fg = c.orange_dark },
    CmpItemKindEnum        = { fg = c.orange_dark },
    CmpItemKindEnumMember  = { fg = c.red },
    CmpItemKindUnit        = { fg = c.orange_dark },
    CmpItemKindModule      = { fg = c.orange_dark },
    CmpItemKindProperty    = { fg = c.fg },
    CmpItemKindField       = { fg = c.fg },
    CmpItemKindOperator    = { fg = c.fg },
    CmpItemKindSnippet     = { fg = c.cyan },
    CmpItemKindText        = { fg = c.fg },
    CmpItemKindFile        = { fg = c.cyan },
    CmpItemKindFolder      = { fg = c.orange },
    CmpItemKindColor       = { fg = c.orange },

    BlinkCmpMenu              = { link = "Pmenu" },
    BlinkCmpMenuBorder        = { fg = c.bg_alt, bg = c.bg },
    BlinkCmpMenuSelection     = { link = "PmenuSel" },
    BlinkCmpLabel             = { fg = c.fg },
    BlinkCmpLabelMatch        = { fg = c.orange, bold = true },
    BlinkCmpLabelDeprecated   = { fg = c.fg_dim, strikethrough = true },
    BlinkCmpKind              = { fg = c.cyan },
    BlinkCmpSource            = { fg = c.fg_dim },

    -- ===== indent-blankline =====
    IblIndent     = { fg = c.bg_alt },
    IblScope      = { fg = c.orange },
    IblWhitespace = { fg = c.bg_alt },

    -- ===== Notify =====
    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder  = { fg = c.orange_dark },
    NotifyINFOBorder  = { fg = c.cyan },
    NotifyDEBUGBorder = { fg = c.fg_dim },
    NotifyTRACEBorder = { fg = c.teal },
    NotifyERRORIcon   = { fg = c.red },
    NotifyWARNIcon    = { fg = c.orange_dark },
    NotifyINFOIcon    = { fg = c.cyan },
    NotifyDEBUGIcon   = { fg = c.fg_dim },
    NotifyTRACEIcon   = { fg = c.teal },
    NotifyERRORTitle  = { fg = c.red, bold = true },
    NotifyWARNTitle   = { fg = c.orange_dark, bold = true },
    NotifyINFOTitle   = { fg = c.cyan, bold = true },
    NotifyDEBUGTitle  = { fg = c.fg_dim, bold = true },
    NotifyTRACETitle  = { fg = c.teal, bold = true },

    -- ===== mini.* =====
    MiniStatuslineModeNormal  = { fg = c.bg, bg = c.orange, bold = true },
    MiniStatuslineModeInsert  = { fg = c.bg, bg = c.teal, bold = true },
    MiniStatuslineModeVisual  = { fg = c.bg, bg = c.cyan, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.orange_dark, bold = true },
    MiniStatuslineModeOther   = { fg = c.bg, bg = c.fg_dim, bold = true },
    MiniStatuslineDevinfo     = { fg = c.fg, bg = c.bg_alt },
    MiniStatuslineFilename    = { fg = c.fg_dim, bg = c.bg },
    MiniStatuslineFileinfo    = { fg = c.fg, bg = c.bg_alt },
    MiniStatuslineInactive    = { fg = c.fg_dim, bg = c.bg },

    -- ===== Markdown view =====
    markdownCode             = { fg = c.teal },
    markdownCodeBlock        = { fg = c.teal },
    markdownH1               = { fg = c.orange_dark, bold = true },
    markdownH2               = { fg = c.orange, bold = true },
    markdownH3               = { fg = c.cyan, bold = true },
    markdownLinkText         = { fg = c.red, underline = true },
    markdownUrl              = { fg = c.red, underline = true },

    -- ===== Lazy =====
    LazyNormal               = { link = "NormalFloat" },
    LazyButton               = { fg = c.fg, bg = c.bg_alt },
    LazyButtonActive         = { fg = c.bg, bg = c.orange, bold = true },
    LazyH1                   = { fg = c.bg, bg = c.orange, bold = true },
  }
end

return M
